name: node action # 名称
on: 
  push:
    branches:
      - main

jobs:
  build_and_publish:
    name: log
    runs-on: ubuntu-latest # 运行环境
    steps: # 步骤
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Install Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '12.16.2'
      - run: npm install
      - run: npm run build

      # 上传到服务器
      - name: Publish
        uses: easingthemes/ssh-deploy@v2.1.5
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: log
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: /root
